<?php

namespace GX2CMS\TemplateEngine\Handlebars;

use GX2CMS\Lib\Response;
use GX2CMS\TemplateEngine\Util\StringUtil;

class Context extends \Handlebars\Context
{
    public function __construct($context = null)
    {
        parent::__construct($context);
    }

    public function get($variableName, $strict = false)
    {
        $constant = $this->getConstant($variableName);

        if ($constant) {
            return $constant;
        }
        else if ($variableName === "''") {
            return $variableName;
        }
        else {
            $htmlBlock = $this->htmlBlock($variableName);
            if ($htmlBlock) {
                return $htmlBlock;
            }
            else {
                $val = parent::get($variableName, $strict);
                if ($variableName === 'item' && !$val) {
                    $val = parent::get('@'.$variableName, $strict);
                    if ($val) {
                        return $val;
                    }
                }
            }
        }

        return parent::get($variableName, $strict); // TODO: Change the autogenerated stub
    }

    private function getConstant($varName): string {
        if (is_numeric($varName)) {
            return $varName;
        }
        if (is_bool($varName) || $varName === 'true' || $varName === 'false') {
            return $varName;
        }
        $first = $varName[0];
        $last = $varName[strlen($varName)-1];
        if (($first === "'" && $last === "'") || ($first === '"' && $last === '"')) {
            if ($first === "'" && $last === "'") {
                $varName = substr($varName, 1, -1);
            }
            return $varName;
        }
        if ($first === "[" && $last === "]") {
            $arr = json_decode($varName, true);
            if ($arr) {
                return implode(',', $arr);
            }
            else {
                Response::renderPlaintext("Malformated literal: " . str_replace(array("'", '"'), '', $varName));
            }
        }
        return "";
    }

    private function htmlBlock($varName): string {
        if (StringUtil::hasTag($varName)) {
            return $varName;
        }
        return "";
    }
}